### ISSUE TITLE
Morning Code Review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/apple-homepage#1]

**Comment by Kyle-Law** [comment]
p2p code review by classmate - @Kyle-Law
1)At `nav a`, may try padding: 0.9rem 2.6rem 0.9rem 2rem; to replace all padding styling.
2)Border-radius problem: Apply `border-radius: 7px;` to `nav ul`, then remove 
```
nav a:nth-child(1):hover {
    /* border-radius: 7px; */
}
```
Also, apply `border-radius: 7px 0 0 7px;` to the first `nav a:hover`;

**Comment by patriciachrysy** [comment]
Good job so far Partick, i just wanted to give a small tip:
- Try to position the background image to like on the original
- reduce the size of the nav-bar and center it, also reduce the size of the search section

**Comment by dili021** [comment]
Just some suggestions:
-You gave the apple icon a class but used the nth-child selector in CSS so the class is redundant.
-You can use a <article> instead of <div class="first-article"> at line 28.
-You started out with comments but didn't continue to the end. This is a short HTML so it doesn't matter much, so again, just best practice suggestions.
-This:
.first-article h1,
.first-article h4,
.first-article h5 

can be written like this:

.first-article > h1, h4, h5 {   (if it's just direct children)
or
.first-article h1, h4, h5 {    (for children and grandchildren)

**Comment by nyatindopatrick** [comment]
Thanks for the comments. All the fixes have been applied
